language: scala
jdk: openjdk11
sudo: false
scala:
  - 2.12.8
before_install: umask 0022
script:
  - sbt clean coverage test
after_success:
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage